version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: windows_build
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - 386
      - amd64
      - arm64
    ldflags: >-
      -w -s
    tags: fts5
    binary: dist/{{ .ProjectName }}_windows_{{ .Arch }}

  - id: unix_build
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm64
    ldflags: >-
      -w -s
    tags: fts5
    binary: dist/{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
