name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.x'
          cache: true

      - name: Build
        run: go build --tags fts5 ./...

      - name: Test
        run: go test -race -tags fts5 -v ./...
