name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: |
        go build --tags fts5 -o tmp/fafi2 fafi2

    - name: Test Build
      run: |
        if [ -f tmp/fafi2 ]; then
          echo "Build succeeded"
        else
          echo "Build failed"
          exit 1
        fi
