name: Go Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.24, 1]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Lint
      run: golangci-lint run

    - name: Test
      run: go test -v ./...

    - name: Build
      env:
        MY_ENV_VAR: ${{ secrets.MY_ENV_VAR }}
      run: |
        go build --tags fts5 -o tmp/fafi2 fafi2

    - name: Test Build
      run: |
        if [ -f tmp/fafi2 ]; then
          echo "Build succeeded"
        else
          echo "Build failed"
          exit 1
        fi

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: fafi2-${{ matrix.go-version }}
        path: tmp/fafi2
